"""002_document_processing_fields

Revision ID: a2980a297243
Revises: b7fdf96cc7ae
Create Date: 2026-08-19 01:48:56.915948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2980a297243'
down_revision: Union[str, Sequence[str], None] = 'b7fdf96cc7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.execute("ALTER TYPE documentstatus RENAME VALUE 'READY' TO 'COMPLETED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE documentstatus RENAME VALUE 'COMPLETED' TO 'READY'")
    op.drop_column('documents', 'processed_at')
    # ### end Alembic commands ###
